name: Deploy Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy Website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn turbo run build --filter=superdjs-website

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd=apps/superdjs-website
